from ..services import funcionario_service, cliente_service, mecanico_service, chefe_service, recepcionista_service, faturista_service, auxiliar_de_faturista_service, oficina_service, loja_conveniada_service, produto_service, veiculos_service, servico_service, tabela_de_precos_service, etapa_servico_services, ordem_servico_service, item_OS_service, solicitacao_reboque_service, nota_fiscal_service, item_NF_service, nota_fiscal_servico_service, titulos_service

funcionario_service.criar_tabela()
cliente_service.criar_tabela()
mecanico_service.criar_tabela()
chefe_service.criar_tabela()
recepcionista_service.criar_tabela()
faturista_service.criar_tabela()
auxiliar_de_faturista_service.criar_tabela()
oficina_service.criar_tabela()
loja_conveniada_service.criar_tabela()
produto_service.criar_tabela()
veiculos_service.criar_tabela()
servico_service.criar_tabela()
tabela_de_precos_service.criar_tabela()
etapa_servico_services.criar_tabela()
ordem_servico_service.criar_tabela()
item_OS_service.criar_tabela()
solicitacao_reboque_service.criar_tabela()
nota_fiscal_service.criar_tabela()
item_NF_service.criar_tabela()
nota_fiscal_servico_service.criar_tabela()
titulos_service.criar_tabela()